# frozen_string_literal: true

require_relative "lib/minitest/openapi/ui/version"

Gem::Specification.new do |spec|
  spec.name = "rc-minitest-openapi-ui"
  spec.version = Minitest::OpenAPI::UI::VERSION
  spec.authors = ["RailsComposer"]
  spec.summary = "Swagger UI for the OpenAPI document generated by rc-minitest-openapi."
  spec.description = "A mountable Rails engine that renders Swagger UI for an OpenAPI " \
    "document, intended to pair with rc-minitest-openapi and rc-minitest-openapi-api."
  spec.homepage = "https://github.com/RailsComposer/minitest-openapi"
  spec.license = "MIT"
  spec.required_ruby_version = ">= 3.2"

  spec.metadata = {
    "homepage_uri" => spec.homepage,
    "source_code_uri" => spec.homepage,
    "rubygems_mfa_required" => "true"
  }

  spec.files = Dir["lib/**/*", "config/**/*", "README.md"]
  spec.require_paths = ["lib"]

  spec.add_dependency "railties", ">= 7.1"
end
