# frozen_string_literal: true

require_relative "lib/minitest/openapi/api/version"

Gem::Specification.new do |spec|
  spec.name = "rc-minitest-openapi-api"
  spec.version = Minitest::OpenAPI::Api::VERSION
  spec.authors = ["RailsComposer"]
  spec.summary = "Serve the OpenAPI document generated by rc-minitest-openapi."
  spec.description = "A mountable Rails engine that serves the OpenAPI document produced " \
    "by rc-minitest-openapi at a configurable route."
  spec.homepage = "https://github.com/RailsComposer/minitest-openapi"
  spec.license = "MIT"
  spec.required_ruby_version = ">= 3.2"

  spec.metadata = {
    "homepage_uri" => spec.homepage,
    "source_code_uri" => spec.homepage,
    "rubygems_mfa_required" => "true"
  }

  spec.files = Dir["lib/**/*", "config/**/*", "README.md"]
  spec.require_paths = ["lib"]

  spec.add_dependency "railties", ">= 7.1"
end
